### ISSUE TITLE
Camera not found

### ISSUE THREAD

**Issue by NonayMete** [TheGuyWhoCodes/LiftTracker#4] opened 2017-02-11 02:48 UTC
We are running your code on a raspberry pi 3 and encountered an issue with the camera not being found. We changed the code in proccessing.java to our team number and compiled the project. It runs happily but we get a long line of "didn't find camera". We have the raspberry pi connecting through ethernet to our router and a Microsoft LifeCam 3000 plugged into the RoboRio. When we put the link "http://roborio-5663-frc.1181/?action=stream" into the web browser on the raspberry pi we get very laggy camera footage. Why is it that we can see the camera stream through the browser (very laggy for some reason?) but the code isn't finding it?  Any advice would be highly appreciated, team 5663.

**Comment by TheGuyWhoCodes** [comment] 2017-02-11 04:10
What I might try is running it straight through the pi and seeing how that works out

**Comment by vyrotek** [comment] 2017-02-11 18:34
We're having similar issues. We're able to open the stream if we use a local camera "0" but we can't get it to process something from the roborio http url. We confirmed the stream is indeed available by going to the URL in Chrome viewing the live feed.

I found some people online mention that they had to also include opencv_ffmpeg320_64.dll when trying to open a remote stream. 

When I include that dll in the natives for opencv-320.jar we get:

A fatal error has been detected by the Java Runtime Environment: EXCEPTION_ACCESS_VIOLATION

Event: 0.023 Thread 0x0000000002f10800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x000000076b407c78) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u111\7883\hotspot\

**Comment by vyrotek** [comment] 2017-02-11 21:00
We were able to fix the exception by removing these lines from Processing.java:
`import org.opencv.imgcodecs.Imgcodecs;`
`Imgcodecs.imwrite("output.png", matOriginal);`

**Comment by TheGuyWhoCodes** [comment] 2017-02-12 00:12
@vyrotek so the error is going away? can you give me a complete log of what errors you saw? did the program crash or did it crash and give you .txt file?

**Comment by vyrotek** [comment] 2017-02-13 15:27
Yes, with the ffmpeg.dll change I mentioned we were able to get it running. 

Here's the log file from the crash. [error.txt](https://github.com/TheGuyWhoCodes/LiftTracker/files/771437/error.txt)

We stumbled  onto the fix by attempting to use OpenCV 2.4.1 instead of 3.2.0. When we tried that we noticed there were only a few lines of code that broke. One of them being the Imgcodec which made us take a closer look at whether it was essential. We noticed it was required for the line `Imgcodecs.imwrite("output.png", matOriginal)` and so we tried removing it and things started working.

We'd like to see what that generated MAT png image looks like. Perhaps you could shed some light on the issue @TheGuyWhoCodes ?

**Comment by TheGuyWhoCodes** [comment] 2017-02-13 17:11
There isn't really much more light to shed, all the Imgcodec line does was to output an image for testing, and I didn't know it needed the ffmpeg DLL file. You can comment that out if you want to, it's not essential @vyrotek

**Comment by vyrotek** [comment] 2017-02-13 18:22
I don't think the Imgcodec needs ffmpeg. ffmpeg is needed to capture a stream over http with `VideoCapture`. Once we got that working then the `Imgcodecs.imwrite` threw the `NoSuchMethodError` exception contained in the error.txt I attached. We haven't figured out what  `Imgcodecs.imwrite` needs in order to work yet.

Update - Hmm, there seems to be a suspicious link between http and Imgcodec.imwrite. The code seems to perform an `imwrite` and create an `output.png` just fine if you capture video from a local camera using `videoCapture.open(1);` but not when providing a http url.

**Comment by TheGuyWhoCodes** [comment] 2017-04-01 18:18
@vyrotek so I looked back through that error.txt file inside of your problem, an I know why it wasn't working.

When I first make the centerX value, it's null. If GRIP finds nothing that is the center, then it will try to push null to network tables, which will cause a crash.

`edu.wpi.first.wpilibj.networktables.NetworkTablesJNI.putDoubleArray`

that was one of the lines in there, and that line relates to the double array from the centerX. 

It will be fixed next commit

**Closed as completed** 2017-05-17 22:22 UTC
Labels: question
